version: '3'
services:
  nats:
    image: nats:2.10.9-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
      - "9090:9090"
    volumes:
      - ./dk.conf:/usr/src/app/dk.conf
    command: ["nats-server","-c","/usr/src/app/dk.conf"]
    
